### ISSUE TITLE
adblockhttpd stops

### ISSUE THREAD

**Issue by ntadmin** [ntadmin/DGND3700v2#39]
Fairly quickly, but at present with no clear cause, the httpd server for the adblock message stops.

**Comment by VincentYbarra** [comment]
Had this happen a few times, I just end up rebooting.

**Comment by ntadmin** [comment]
Glad to hear that that sorts it, I'm hoping we can make it not need the reboot. I'll be working on this one once I've got the allow list working.

**Comment by VincentYbarra** [comment]
Awesome! Can't wait! 
Thanks for doing all of this btw!

**Comment by ntadmin** [comment]
No worries - but please don't hold your breath: I'm doing this a couple of hours every week, so progress isn't quick :-)
Out of interest, what version are you using? Or are you building from the git source?

**Comment by VincentYbarra** [comment]
Doing more work than netgear (better)
Beta release 3

**Comment by ntadmin** [comment]
Thanks - I'm hoping for a next beta by the end of September, which should solidify all the various things to date. But life my have other plans!

**Comment by VincentYbarra** [comment]
Had it happen again, this time I didn't reboot.. It ended up fixing itself..about in 5-20mins

**Comment by ntadmin** [comment]
Interesting. Nice that it started up again, but I suspect that that was a fortuitous accident as I certainly haven't put in any code to achieve the effect! I'm still trying to track exactly what make sit fail ...

**Comment by ntadmin** [comment]
Although it would have been good to get this one nailed, an updated beta is important, so we have let this one slip.

**Comment by ntadmin** [comment]
OK, latest commits mean it now runs for days, so we'll close this one down. If it crashes in the future, better to open a new issue.
